class Country < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Afghanistan' },
    { id: 3, name: 'Albania' },
    { id: 4, name: 'Algeria' },
    { id: 5, name: 'Andorra' },
    { id: 6, name: 'Angola' },
    { id: 7, name: 'Antigua and Barbuda' },
    { id: 8, name: 'Argentina' },
    { id: 9, name: 'Armenia' },
    { id: 10, name: 'Australia' },
    { id: 11, name: 'Austria' },
    { id: 12, name: 'Azerbaijan' },
    { id: 13, name: 'Bahamas' },
    { id: 14, name: 'Bahrain' },
    { id: 15, name: 'Bangladesh' },
    { id: 16, name: 'Barbados' },
    { id: 17, name: 'Belarus' },
    { id: 18, name: 'Belgium' },
    { id: 19, name: 'Belize' },
    { id: 20, name: 'Benin' },
    { id: 21, name: 'Bhutan' },
    { id: 22, name: 'Bolivia' },
    { id: 23, name: 'Bosnia and Herzegovina' },
    { id: 24, name: 'Botswana' },
    { id: 25, name: 'Brazil' },
    { id: 26, name: 'Brunei Darussalam' },
    { id: 27, name: 'Bulgaria' },
    { id: 28, name: 'Burkina Faso' },
    { id: 29, name: 'Burundi' },
    { id: 30, name: 'Cabo Verde' },
    { id: 31, name: 'Cambodia' },
    { id: 32, name: 'Cameroon' },
    { id: 33, name: 'Canada' },
    { id: 34, name: 'Central African Republic' },
    { id: 35, name: 'Chad' },
    { id: 36, name: 'Chile' },
    { id: 37, name: 'China' },
    { id: 38, name: 'Colombia' },
    { id: 39, name: 'Comoros' },
    { id: 40, name: 'Congo' },
    { id: 41, name: 'Costa Rica' },
    { id: 42, name: "Cote d'Ivoire" },
    { id: 43, name: 'Croatia' },
    { id: 44, name: 'Cuba' },
    { id: 45, name: 'Cyprus' },
    { id: 46, name: 'Czech Republic' },
    { id: 47, name: "Democratic People's Republic of Korea" },
    { id: 48, name: 'Democratic Republic of the Congo' },
    { id: 49, name: 'Denmark' },
    { id: 50, name: 'Djibouti' },
    { id: 51, name: 'Dominica' },
    { id: 52, name: 'Dominican Republic' },
    { id: 53, name: 'Ecuador' },
    { id: 54, name: 'Egypt' },
    { id: 55, name: 'El Salvador' },
    { id: 56, name: 'Equatorial Guinea' },
    { id: 57, name: 'Eritrea' },
    { id: 58, name: 'Estonia' },
    { id: 59, name: 'Eswatini' },
    { id: 60, name: 'Ethiopia' },
    { id: 61, name: 'Fiji' },
    { id: 62, name: 'Finland' },
    { id: 63, name: 'France' },
    { id: 64, name: 'Gabon' },
    { id: 65, name: 'Gambia' },
    { id: 66, name: 'Georgia' },
    { id: 67, name: 'Germany' },
    { id: 68, name: 'Ghana' },
    { id: 69, name: 'Greece' },
    { id: 70, name: 'Grenada' },
    { id: 71, name: 'Guatemala' },
    { id: 72, name: 'Guinea' },
    { id: 73, name: 'Guinea-Bissau' },
    { id: 74, name: 'Guyana' },
    { id: 75, name: 'Haiti' },
    { id: 76, name: 'Honduras' },
    { id: 77, name: 'Hungary' },
    { id: 78, name: 'Iceland' },
    { id: 79, name: 'India' },
    { id: 80, name: 'Indonesia' },
    { id: 81, name: 'Iran' },
    { id: 82, name: 'Iraq' },
    { id: 83, name: 'Ireland' },
    { id: 84, name: 'Israel' },
    { id: 85, name: 'Italy' },
    { id: 86, name: 'Jamaica' },
    { id: 87, name: 'Japan' },
    { id: 88, name: 'Jordan' },
    { id: 89, name: 'Kazakhstan' },
    { id: 90, name: 'Kenya' },
    { id: 91, name: 'Kiribati' },
    { id: 92, name: 'Korea' },
    { id: 93, name: 'Kuwait' },
    { id: 94, name: 'Kyrgyzstan' },
    { id: 95, name: "Lao People's Democratic Republic" },
    { id: 96, name: 'Latvia' },
    { id: 97, name: 'Lebanon' },
    { id: 98, name: 'Lesotho' },
    { id: 99, name: 'Liberia' },
    { id: 100, name: 'Libya' },
    { id: 101, name: 'Liechtenstein' },
    { id: 102, name: 'Lithuania' },
    { id: 103, name: 'Luxembourg' },
    { id: 104, name: 'Madagascar' },
    { id: 105, name: 'Malawi' },
    { id: 106, name: 'Malaysia' },
    { id: 107, name: 'Maldives' },
    { id: 108, name: 'Mali' },
    { id: 109, name: 'Malta' },
    { id: 110, name: 'Marshall Islands' },
    { id: 111, name: 'Mauritania' },
    { id: 112, name: 'Mauritius' },
    { id: 113, name: 'Mexico' },
    { id: 114, name: 'Micronesia' },
    { id: 115, name: 'Monaco' },
    { id: 116, name: 'Mongolia' },
    { id: 117, name: 'Montenegro' },
    { id: 118, name: 'Morocco' },
    { id: 119, name: 'Mozambique' },
    { id: 120, name: 'Myanmar' },
    { id: 121, name: 'Namibia' },
    { id: 122, name: 'Nauru' },
    { id: 123, name: 'Nepal' },
    { id: 124, name: 'Netherlands' },
    { id: 125, name: 'New Zealand' },
    { id: 126, name: 'Nicaragua' },
    { id: 127, name: 'Niger' },
    { id: 128, name: 'Nigeria' },
    { id: 129, name: 'North Macedonia' },
    { id: 130, name: 'Norway' },
    { id: 131, name: 'Oman' },
    { id: 132, name: 'Pakistan' },
    { id: 133, name: 'Palau' },
    { id: 134, name: 'Panama' },
    { id: 135, name: 'Papua New Guinea' },
    { id: 136, name: 'Paraguay' },
    { id: 137, name: 'Peru' },
    { id: 138, name: 'Philippines' },
    { id: 139, name: 'Poland' },
    { id: 140, name: 'Portugal' },
    { id: 141, name: 'Qatar' },
    { id: 142, name: 'Republic of Korea' },
    { id: 143, name: 'Republic of Moldova' },
    { id: 144, name: 'Romania' },
    { id: 145, name: 'Russian Federation' },
    { id: 146, name: 'Rwanda' },
    { id: 147, name: 'Saint Kitts and Nevis' },
    { id: 148, name: 'Saint Lucia' },
    { id: 149, name: 'Saint Vincent and the Grenadines' },
    { id: 150, name: 'Samoa' },
    { id: 151, name: 'San Marino' },
    { id: 152, name: 'Sao Tome and Principe' },
    { id: 153, name: 'Saudi Arabia' },
    { id: 154, name: 'Senegal' },
    { id: 155, name: 'Serbia' },
    { id: 156, name: 'Seychelles' },
    { id: 157, name: 'Sierra Leone' },
    { id: 158, name: 'Singapore' },
    { id: 159, name: 'Slovakia' },
    { id: 160, name: 'Slovenia' },
    { id: 161, name: 'Solomon Islands' },
    { id: 162, name: 'Somalia' },
    { id: 163, name: 'South Africa' },
    { id: 164, name: 'South Sudan' },
    { id: 165, name: 'Spain' },
    { id: 166, name: 'Sri Lanka' },
    { id: 167, name: 'Sudan' },
    { id: 168, name: 'Suriname' },
    { id: 169, name: 'Sweden' },
    { id: 170, name: 'Switzerland' },
    { id: 171, name: 'Syria' },
    { id: 172, name: 'Taiwan' },
    { id: 173, name: 'Tajikistan' },
    { id: 174, name: 'Thailand' },
    { id: 175, name: 'Timor-Leste' },
    { id: 176, name: 'Togo' },
    { id: 177, name: 'Tonga' },
    { id: 178, name: 'Trinidad and Tobago' },
    { id: 179, name: 'Tunisia' },
    { id: 180, name: 'Turkey' },
    { id: 181, name: 'Turkmenistan' },
    { id: 182, name: 'Tuvalu' },
    { id: 183, name: 'Uganda' },
    { id: 184, name: 'Ukraine' },
    { id: 185, name: 'United Arab Emirates' },
    { id: 186, name: 'United Kingdom' },
    { id: 187, name: 'United Republic of Tanzania' },
    { id: 188, name: 'United States of America' },
    { id: 189, name: 'Uruguay' },
    { id: 190, name: 'Uzbekistan' },
    { id: 191, name: 'Vanuatu' },
    { id: 192, name: 'Venezuela' },
    { id: 193, name: 'Viet Nam' },
    { id: 194, name: 'Yemen' },
    { id: 195, name: 'Zambia' },
    { id: 196, name: 'Zimbabwe' },
    { id: 197, name: 'Other' },
  ]

  include ActiveHash::Associations
  has_many :areas
end