class Language < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Afrikaans : Afrikaans' },
    { id: 3, name: 'Albanian : Shqip' },
    { id: 4, name: 'Arabic : العربية' },
    { id: 5, name: 'Armenian : Հայերեն' },
    { id: 6, name: 'Assamese : অসমীয়া' },
    { id: 7, name: 'Azerbaijani : Azərbaycan dili' },
    { id: 8, name: 'Basque : Euskara' },
    { id: 9, name: 'Belarusian : Беларуская мова' },
    { id: 10, name: 'Bengali : বাংলা' },
    { id: 11, name: 'Bosnian : Bosanski' },
    { id: 12, name: 'Bulgarian : Български' },
    { id: 13, name: 'Catalan : Català' },
    { id: 14, name: 'Cebuano : Cebuano' },
    { id: 15, name: 'Chinese (China) : 简体中文' },
    { id: 16, name: 'Chinese (Hong Kong) : 香港中文版' },
    { id: 17, name: 'Chinese (Taiwan) : 繁體中文' },
    { id: 18, name: 'Croatian : Hrvatski' },
    { id: 19, name: 'Czech : Čeština' },
    { id: 20, name: 'Danish : Dansk' },
    { id: 21, name: 'Dutch : Nederlands' },
    { id: 22, name: 'Dzongkha : རྫོང་ཁ' },
    { id: 23, name: 'English' },
    { id: 24, name: 'Esperanto' },
    { id: 25, name: 'Estonian : Eesti' },
    { id: 26, name: 'Finnish : Suomi' },
    { id: 27, name: 'French : Français' },
    { id: 28, name: 'Friulian' },
    { id: 29, name: 'Galician : Galego' },
    { id: 30, name: 'Georgian : ქართული' },
    { id: 31, name: 'German : Deutsch' },
    { id: 32, name: 'Greek : Ελληνικά' },
    { id: 33, name: 'Gujarati : ગુજરાતી' },
    { id: 34, name: 'Hazaragi : هزاره گی' },
    { id: 35, name: 'Hebrew : עִבְרִית' },
    { id: 36, name: 'Hindi : हिन्दी' },
    { id: 37, name: 'Hungarian : Magyar' },
    { id: 38, name: 'Icelandic : Íslenska' },
    { id: 39, name: 'Indonesian : Bahasa Indonesia' },
    { id: 40, name: 'Italian : Italiano' },
    { id: 41, name: 'Japanese : 日本語' },
    { id: 42, name: 'Javanese : Basa Jawa' },
    { id: 43, name: 'Kabyle : Taqbaylit' },
    { id: 44, name: 'Kazakh : Қазақ тілі' },
    { id: 45, name: 'Khmer : ភាសាខ្មែរ' },
    { id: 46, name: 'Korean : 한국어' },
    { id: 47, name: 'Kurdish (Sorani) : كوردی' },
    { id: 48, name: 'Lao : ພາສາລາວ' },
    { id: 49, name: 'Latvian : Latviešu valoda' },
    { id: 50, name: 'Lithuanian : Lietuvių kalba' },
    { id: 51, name: 'Macedonian : Македонски јазик' },
    { id: 52, name: 'Malay : Bahasa Melayu' },
    { id: 53, name: 'Malayalam : മലയാളം' },
    { id: 54, name: 'Marathi : मराठी' },
    { id: 55, name: 'Mongolian : Монгол' },
    { id: 56, name: 'Moroccan Arabic : العربية المغربية' },
    { id: 57, name: 'Myanmar (Burmese) : ဗမာစာ' },
    { id: 58, name: 'Nepali : नेपाली' },
    { id: 59, name: 'Norwegian : Norsk' },
    { id: 60, name: 'Occitan : Occitan' },
    { id: 61, name: 'Pashto : پښت' },
    { id: 62, name: 'Persian : فارسی' },
    { id: 63, name: 'Polish : Polski' },
    { id: 64, name: 'Portuguese : Português' },
    { id: 65, name: 'Punjabi : ਪੰਜਾਬੀ' },
    { id: 66, name: 'Rohingya : Ruáinga' },
    { id: 67, name: 'Romanian : Română' },
    { id: 68, name: 'Russian : Русский' },
    { id: 69, name: 'Sakha : Сахалыы' },
    { id: 70, name: 'Scottish Gaelic : Gàidhlig' },
    { id: 71, name: 'Serbian : Српски језик' },
    { id: 72, name: 'Silesian : Ślōnskŏ gŏdka' },
    { id: 73, name: 'Sinhala : සිංහල' },
    { id: 74, name: 'Slovak : Slovenčina' },
    { id: 75, name: 'Slovenian : Slovenščina' },
    { id: 76, name: 'South Azerbaijani : گؤنئی آذربایجان' },
    { id: 77, name: 'Spanish : Español' },
    { id: 78, name: 'Swedish : Svenska' },
    { id: 79, name: 'Tagalog : Tagalog' },
    { id: 80, name: 'Tahitian : Reo Tahiti' },
    { id: 81, name: 'Tamil : தமிழ்' },
    { id: 82, name: 'Tatar : Татар теле' },
    { id: 83, name: 'Telugu : తెలుగు' },
    { id: 84, name: 'Thai : ไทย' },
    { id: 85, name: 'Tibetan : བོད་ཡིག' },
    { id: 86, name: 'Turkish : Türkçe' },
    { id: 87, name: 'Uighur : ئۇيغۇرچە' },
    { id: 88, name: 'Ukrainian : Українська' },
    { id: 89, name: 'Urdu : اردو' },
    { id: 90, name: 'Uzbek : O‘zbekcha' },
    { id: 91, name: 'Vietnamese : Tiếng Việt' },
    { id: 92, name: 'Welsh : Cymraeg' },
    { id: 93, name: 'Other' },
  ]

  include ActiveHash::Associations
  has_many :areas
end